vulnerabilities:
  - id: CVE-2026-65182
    statement: "Tomcat 10.1.58 not yet published to Maven Central"
  - id: CVE-2026-65905
    statement: "Tomcat 10.1.58 not yet published to Maven Central"
  - id: CVE-2026-68525
    statement: "Tomcat 10.1.58 not yet published to Maven Central"
