# Expor endpoints do Actuator
management.endpoints.web.exposure.include=health,info

# Mostrar detalhes extras no health check (opcional, mas boa prática)
management.endpoint.health.show-details=always

# Configuração externa (Será sobrescrita por variável de ambiente no ECS)
APP_FEATURE_FLAG=false