# Expor endpoints do Actuator
management.endpoints.web.exposure.include=health,info

# Restringir detalhes de saude para nao expor informacoes sensiveis publicamente
management.endpoint.health.show-details=never

# Configuração externa (Será sobrescrita por variável de ambiente no ECS)
APP_FEATURE_FLAG=false